using PineCone.BuildingBlocks.Data.Constants;

namespace DocumentGenerator.Models
{
    public static class EntityFieldArrays
    {
        public static Dictionary<string, List<string>> ArrayFieldsByEntity = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase)
        {
            //case entity:
            {TemplateEntities.Case, new List<string>{"CaseID", "Type", "CaseStatusMasterCode", "Status"}},
            {TemplateEntities.CaseAgency, new List<string>{"CaseAgencyID", "NumberType"}},
            {TemplateEntities.CaseArrestInfo, new List<string>{"CaseArrestInfoID"}},
            {TemplateEntities.CaseAssignment, new List<string>{"CaseAssignmentID", "Type"}},
            {TemplateEntities.CaseBond, new List<string>{"CaseBondID", "Type"}},
            {TemplateEntities.CaseBondCondition, new List<string>{"CaseBondConditionID", "Type"}},
            {TemplateEntities.CaseCategory, new List<string>{"CaseCategoryID"}},
            {TemplateEntities.CaseCharge, new List<string>{"CaseChargeID", "Stage", "Decision"}},
            {TemplateEntities.CaseChargeElement, new List<string>{"CaseChargeElementID", "Type"}},
            {TemplateEntities.CaseChargeExhibit, new List<string>{"CaseChargeExhibitID"}},
            {TemplateEntities.CaseChargeHistory, new List<string>{"CaseChargeHistoryID"}},
            {TemplateEntities.CaseChargeIntoxicant, new List<string>{"CaseChargeIntoxicantID", "Type"}},
            {TemplateEntities.CaseChargeInvolvement, new List<string>{"CaseChargeInvolvementID"}},
            {TemplateEntities.CaseChargeLanguage, new List<string>{"CaseChargeLanguageID", "Type"}},
            {TemplateEntities.CaseCorrespondence, new List<string>{"CaseCorrespondenceID", "Type", "Location"}},
            {TemplateEntities.CaseCorrespondenceAssignment, new List<string>{"CaseCorrespondenceAssignmentID"}},
            {TemplateEntities.CaseCorrespondenceInvolvement, new List<string>{"CaseCorrespondenceInvolvementID"}},
            {TemplateEntities.CaseCorrespondenceMediaItem, new List<string>{"CaseCorrespondenceMediaItemID"}},
            {TemplateEntities.CaseCorrespondenceResult, new List<string>{"CaseCorrespondenceResultID"}},
            {TemplateEntities.CaseDisposition, new List<string>{"CaseDispositionID", "Type"}},
            {TemplateEntities.CaseDrugTest, new List<string>{"CaseDrugTestID", "Type", "Location", "Status"}},
            {TemplateEntities.CaseDrugTestResult, new List<string>{"CaseDrugTestResultID", "Status"}},
            {TemplateEntities.CaseElement, new List<string>{"CaseElementID", "Type", "Subtype"}},
            {TemplateEntities.CaseExhibit, new List<string>{"CaseExhibitID", "Type"}},
            {TemplateEntities.CaseFee, new List<string>{"CaseFeeID"}},
            {TemplateEntities.CaseFlag, new List<string>{ "CaseFlagID", "Type", "Subtype"}},
            {TemplateEntities.CaseInvolvement, new List<string>{"CaseInvolvementID", "Type"}},
            {TemplateEntities.CaseMediaFolder, new List<string>{"MediaFolderID"}},
            //{TemplateEntities.CaseNameTemplate, new List<string>{}},
            {TemplateEntities.CaseNote, new List<string>{"CaseNoteID", "Type"}},
            {TemplateEntities.CasePlea, new List<string>{"CasePleaID", "Type"}},
            {TemplateEntities.CasePleaAgreement, new List<string>{"CasePleaAgreementID"}},
            {TemplateEntities.CaseRelationship, new List<string>{"CaseRelationshipID"}},
            {TemplateEntities.CaseSentence, new List<string>{"CaseSentenceID"}},
            {TemplateEntities.CaseSentenceCondition, new List<string>{"CaseSentenceConditionID"}},
            {TemplateEntities.CaseSentenceTimeTracking, new List<string>{"CaseSentenceTimeTrackingID", "Type", "Status"}},
            {TemplateEntities.CaseStatusHistory, new List<string>{"CaseStatusHistoryID"}},
            {TemplateEntities.CaseTimeTracking, new List<string>{"CaseTimeTrackingID", "Type"}},
            // event entity
            {TemplateEntities.Event, new List<string>{"EventID", "Type"}},
            {TemplateEntities.EventAssignment, new List<string>{"EventAssignmentID", "Type", "Subtype", "Status"}},
            {TemplateEntities.EventInvolvement, new List<string>{ "EventInvolvementID", "Type", "Subtype", "Status"}},
            {TemplateEntities.EventMediaItem, new List<string>{"EventMediaItemID"}},
            {TemplateEntities.EventResult, new List<string>{"EventResultID"}},
            {TemplateEntities.Task, new List<string>{"TaskID", "Type", "Location"}},
            {TemplateEntities.TaskAssignment, new List<string>{"TaskAssignmentID"}},
            {TemplateEntities.TaskMediaItem, new List<string>{"TaskMediaItemID"}},
            {TemplateEntities.TaskResult, new List<string>{"TaskResultID"}},
            // name entity
            {TemplateEntities.Name, new List<string>{"NameID"}},
            {TemplateEntities.NameAddress, new List<string>{"NameAddressID"}},
            {TemplateEntities.NameCorrespondence, new List<string>{"NameCorrespondenceID"}},
            {TemplateEntities.NameCorrespondenceAssignment, new List<string>{"NameCorrespondenceAssignmentID"}},
            {TemplateEntities.NameCorrespondenceInvolvement, new List<string>{"NameCorrespondenceInvolvementID"}},
            {TemplateEntities.NameCorrespondenceMediaItem, new List<string>{"NameCorrespondenceMediaItemID"}},
            {TemplateEntities.NameCorrespondenceResult, new List<string>{"NameCorrespondenceResultID"}},
            {TemplateEntities.NameElement, new List<string>{"NameElementID"}},
            {TemplateEntities.NameEmail, new List<string>{"NameEmailID"}},
            {TemplateEntities.NameFlag, new List<string>{"NameFlagID"}},
            {TemplateEntities.NameImage, new List<string>{"NameImageID"}},
            {TemplateEntities.NameMediaFolder, new List<string>{"MediaFolderID"}},
            {TemplateEntities.NameNote, new List<string>{"NameNoteID"}},
            {TemplateEntities.NameNumber, new List<string>{"NameNumberID", "Type"}},
            {TemplateEntities.NamePhone, new List<string>{"NamePhoneID"}},
            {TemplateEntities.NameRelationship, new List<string>{"NameRelationshipID", "Type"}},
            // personnel entity
            {TemplateEntities.Personnel, new List<string>{"PersonnelID"}},
            {TemplateEntities.PersonnelAddress, new List<string>{"PersonnelAddressID"}},
            {TemplateEntities.PersonnelAgency, new List<string>{"PersonnelAgencyID"}},
            {TemplateEntities.PersonnelElement, new List<string>{"PersonnelElementID"}},
            {TemplateEntities.PersonnelEmail, new List<string>{"PersonnelEmailID"}},
            {TemplateEntities.PersonnelFlag, new List<string>{"PersonnelFlagID"}},
            {TemplateEntities.PersonnelImage, new List<string>{"PersonnelImageID"}},
            {TemplateEntities.PersonnelMediaFolder, new List<string>{"MediaFolderID"}},
            {TemplateEntities.PersonnelNumber, new List<string>{"PersonnelNumberID", "Type"}},
            {TemplateEntities.PersonnelPhone, new List<string>{"PersonnelPhoneID"}},
            {TemplateEntities.PersonnelTeam, new List<string>{"PersonnelTeamID"}},
            // system entity
            {TemplateEntities.SystemUser, new List<string>{"SystemUserID"}},
            {TemplateEntities.SecurityLog, new List<string>{}},
            {TemplateEntities.SystemAgency, new List<string>{"SystemAgencyID", "Type", "Subtype"}},
            {TemplateEntities.SystemAgencyAddress, new List<string>{"SystemAgencyAddressID"}},
            {TemplateEntities.SystemAgencyEmail, new List<string>{"SystemAgencyEmailID"}},
            {TemplateEntities.SystemAgencyPhone, new List<string>{"SystemAgencyPhoneID"}},
            {TemplateEntities.SystemStatute, new List<string>{"SystemStatuteID", "CodeSource", "Severity", "Class", "Category"}},
            {TemplateEntities.SystemStatuteChargingLanguage, new List<string>{"SystemStatuteChargingLanguageID"}},
            {TemplateEntities.SystemStatuteElement, new List<string>{"SystemStatuteElementID"}},
            {TemplateEntities.SystemStatuteText, new List<string>{"SystemStatuteTextID", "Type"}},
            {TemplateEntities.Payment, new List<string>{"PaymentID"}},
            {TemplateEntities.PaymentObligationAllocation, new List<string>{"PaymentObligationAllocationID"}},
            { TemplateEntities.SystemSetting, new List<string>{ "SystemSettingID", "Status" } }
        };
    }
}
