from pydantic import BaseModel
from typing import Any, Dict, List, Optional
from langchain_core.messages import SystemMessage, ToolMessage, AIMessage
from prompts import extraction_prompt, mapping_prompt, generation_prompt
from striprtf.striprtf import rtf_to_text

class mappings(BaseModel):
    """Defines the structure of mappings for the legacy and pine variables and their confidence scores."""
    legacy: str
    pine: str
    confidence: str

def make_extraction_call(model):
    """Makes a call to the LLM to perform the extraction process
    
    Args:
        model: The LLM model to use for planning
    """
    def extraction_call(state: dict):
        """ The llm makes the extration based on the plan it made in the previous step"""
        response = model.invoke(
            [
                SystemMessage(
                    content=extraction_prompt(state['legacy_template'])
                )
            ]
        )

        extracted_vars = [
            line.strip()
            for line in response.content.strip().splitlines()
            if line.strip()
        ]
        print("Extracting variables and functions from legacy template")
        return {
            "messages": [response],
            "llm_calls": state.get('llm_calls', 0) + 1,
            "extracted_legacy_info": extracted_vars,
        }
    
    return extraction_call

def make_mapping_call(model):
    """Makes a call to the LLM to perform the mapping of the extracted
       variables and functions to the Pine syntax
    
    Args:
        model: The LLM model to use for planning
    """
    def mapping_call(state: dict):
        """ The llm makes the mapping based on the plan it made in the previous step"""
        tool_messages = [
            m for m in state["messages"]
            if isinstance(m, ToolMessage) or (isinstance(m, AIMessage) and m.tool_calls)
        ]
        response = model.invoke(
            [
                SystemMessage(
                    content=mapping_prompt(state['extracted_legacy_info'])
                )
            ]
            + tool_messages
        )

        extracted_vars = [
            line.strip()
            for line in response.content.strip().splitlines()
            if line.strip()
        ]
        print("Mapping variables to pine syntax")
        return {
            "messages": [response],
            "llm_calls": state.get('llm_calls', 0) + 1,
            "mapping_calls": state.get('mapping_calls', 0) + 1,
            "mapped_pine_info": extracted_vars,
        }
    
    return mapping_call

def make_pine_template_generation_call(model):
    """Make a call to the LLM to generate a Pine template
       based on the mapped variables and functions
    
    Args:
        model: The LLM model to use for planning
    """
    def pine_template_generation_call(state: dict):
        """ The llm generates a pine templated based on the
            mapped legacy to pine variables and functions.
        """
        response = model.invoke(
            [
                SystemMessage(
                    content=generation_prompt(
                        state['legacy_template'],
                        state['mapped_pine_info'],
                        state.get('rtf_validation_error', '')
                    )
                )
            ]
        )
        print("Generating the Pine template")
        return {
            "messages": [response],
            "llm_calls": state.get('llm_calls', 0) + 1,
            "generated_pine_template": response.content,
        }
    
    return pine_template_generation_call

def validate_rtf(state: dict):
    """ Validates that the generated .rtf template is correctly formatted.
        Auto-fixes minor issues (trailing braces, markdown fences).
        Reports unfixable errors for retry.
        This function is generated by Claude.

        Args: state: the current agent state
    """
    import re

    rtf = state["generated_pine_template"]
    errors = []
    warnings = []
    retries = state.get("generation_retries", 0) + 1

    # --- Auto-fix: strip markdown code fences ---
    stripped = rtf.strip()
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        if lines[-1].strip() == "```":
            lines = lines[1:-1]
        else:
            lines = lines[1:]
        rtf = "\n".join(lines)
        stripped = rtf.strip()
        warnings.append("Stripped markdown code fences from output")

    # --- Header check ---
    if not stripped.startswith("{\\rtf1"):
        errors.append("Missing or invalid RTF header: must start with {\\rtf1")

    # --- Brace balance ---
    depth = 0
    for ch in stripped:
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
        if depth < 0:
            errors.append("Unbalanced braces: found closing '}' without matching '{'")
            break

    # Auto-fix small positive depth (missing trailing braces)
    if 0 < depth <= 3:
        stripped += "}" * depth
        rtf = stripped
        warnings.append(f"Auto-appended {depth} closing '}}' to balance braces")
        depth = 0
    elif depth > 3:
        errors.append(f"Unbalanced braces: {depth} unclosed '{{' remaining (too many to auto-fix)")

    if not stripped.endswith("}"):
        errors.append("RTF document does not end with '}' (likely truncated)")

    # --- Control flow balance ---
    if_count = len(re.findall(r'@\[If\b', stripped, re.IGNORECASE))
    endif_count = len(re.findall(r'@\[EndIf\b', stripped, re.IGNORECASE))
    if if_count > endif_count:
        errors.append(f"Truncated control flow: {if_count} @[If] but only {endif_count} @[EndIf]")

    foreach_count = len(re.findall(r'@\[Foreach\b', stripped, re.IGNORECASE))
    endforeach_count = len(re.findall(r'@\[EndForEach\b', stripped, re.IGNORECASE))
    if foreach_count > endforeach_count:
        errors.append(f"Truncated control flow: {foreach_count} @[Foreach] but only {endforeach_count} @[EndForEach]")

    # --- Hex data integrity (themedata) ---
    theme_match = re.search(r'\{\\\*\\themedata\s+([0-9a-fA-F\s]+)\}', stripped)
    if theme_match:
        hex_data = theme_match.group(1).replace(' ', '').replace('\n', '').replace('\r', '')
        if not re.fullmatch(r'[0-9a-fA-F]+', hex_data):
            errors.append("Corrupted themedata: contains non-hex characters")
        elif not hex_data.startswith("504b0304"):
            errors.append("Corrupted themedata: hex does not start with PK ZIP header (504b0304)")

    # --- Hex data integrity (colorschememapping) ---
    csm_match = re.search(r'\{\\\*\\colorschememapping\s+([0-9a-fA-F\s]+)\}', stripped)
    if csm_match:
        hex_data = csm_match.group(1).replace(' ', '').replace('\n', '').replace('\r', '')
        if not re.fullmatch(r'[0-9a-fA-F]+', hex_data):
            errors.append("Corrupted colorschememapping: contains non-hex characters")
        elif not hex_data.startswith("3c3f786d6c"):
            errors.append("Corrupted colorschememapping: hex does not start with XML declaration (3c3f786d6c = <?xml)")

    if warnings:
        print(f"RTF validation warnings: {'; '.join(warnings)}")

    if errors:
        error_msg = "; ".join(errors)
        print(f"RTF validation FAILED: {error_msg}")
        print(f"Retrying generation of Pine template: Attempt {retries}")
        return {"rtf_validation_error": error_msg, "generation_retries": retries, "generated_pine_template": rtf}
    
    print("RTF validation passed")
    return {"rtf_validation_error": "", "generation_retries": retries, "generated_pine_template": stripped}